backend:
  name: github
  repo: apel-prevention/site-apel
  branch: main
  automatic_deployments: false
  base_url: https://sveltia-cms-authenticator.dev-c5f.workers.dev

publish_mode: editorial_workflow
media_folder: static/images/uploads
public_folder: /images/uploads
site_url: https://www.apelprevention.fr/
locale: fr
collections:

  - name: post
    label: Articles
    label_singular: Article
    folder: content/posts
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: Layout, name: layout, widget: hidden, default: blog }
      - { label: Titre, name: title, widget: string }
      - { label: Brouillon, name: draft, widget: boolean, default: true }
      - { label: Auteur, name: author, widget: relation, collection: staff, value_field: title, search_fields: title, required: false }
      - { label: Date de publication, name: date, widget: datetime }
      - { label: Description, name: description, widget: string, required: false, hint: Information affichée dans la miniature lorsque la page est partagée }
      - { label: Images, name: images, widget: list, field: { label: Image, name: image, widget: image }, required: false, hint: Image affichée dans la miniature lorsque la page est partagée }
      - { label: Contenu, name: body, widget: markdown }

  - name: staff
    label: L'équipe
    label_singular: Membre de l'équipe
    icon: group
    folder: content/staff
    create: true
    fields:
      - { label: Nom, name: title, widget: string }
      - { label: Rôle, name: role, widget: string }
      - { label: Ordre d'affichage, name: weight, widget: number, value_type: "int" }
      - { label: Photo, name: image, widget: image, required: false, hint: Photo affichée }
      - { label: Adresse mail, name: email, widget: string, required: false, hint: Utilisé pour récupérer le gravatar associé à l'adresse }
      - label: Réseaux sociaux
        label_singular: Réseau social
        name: socials
        required: false
        widget: list
        fields:
        - { label: Nom, name: name, widget: select, options: ["Twitter", "LinkedIn", "Facebook", "Google"] }
        - { label: Lien, name: url, widget: string }
      - { label: Contenu, name: body, widget: markdown, hint: Contenu }

  - name: references
    label: Références
    label_singular: Référence
    icon: folder_open
    folder: content/references
    create: true
    fields:
      - { label: Nom, name: title, widget: string }
      - { label: Brouillon, name: draft, widget: boolean, default: true }
      - { label: Date de la référence, name: date, widget: datetime }
      - { label: Description, name: description, widget: string, required: false, hint: Information affichée dans la miniature lorsque la page est partagée }
      - { label: Images, name: images, widget: list, field: { label: Image, name: image, widget: image }, required: false, hint: Image affichée dans la miniature lorsque la page est partagée }
      - { label: Contenu, name: body, widget: markdown, hint: Contenu }

  - name: activities
    label: Activités
    label_singular: Activité
    icon: detection_and_zone
    folder: content/activities
    create: true
    fields:
      - { label: Nom, name: title, widget: string }
      - { label: Position, name: weight, widget: number, value_type: "int" }
      - { label: Contenu, name: body, widget: markdown, hint: Contenu }

  - name: pages
    label: Pages statiques
    label_singular: Page statique
    icon: info
    description: Pages statiques
    files:

      - name: home
        label: Page d'accueil
        file: content/_index.md
        fields:
          - { label: Titre, name: title, widget: string, hint: Titre de la page }
          - { label: Description, name: description, widget: string, required: false, hint: Information affichée dans la miniature lorsque la page est partagée }
          - { label: Contenu, name: body, widget: markdown }


      - name: about
        label: Contact
        file: content/contact/_index.md
        fields:
          - { label: Titre, name: title, widget: string, hint: Titre de la page }
          - { label: Description, name: description, widget: string, required: false, hint: Information affichée dans la miniature lorsque la page est partagée }
          - { label: Contenu, name: body, widget: markdown }

      - name: legal
        label: Mentions légales
        file: content/legal/_index.md
        fields:
          - { label: Titre, name: title, widget: string, hint: Titre de la page }
          - { label: Description, name: description, widget: string, required: false, hint: Information affichée dans la miniature lorsque la page est partagée }
          - { label: Contenu, name: body, widget: markdown }
